const Port = process.env.PORT || 8500;
const MONGO_URL = process.env.MONGO_URL;
const IMG_BB_API_KEY = process.env.IMG_BB_API_KEY;
const ADMIN_IDENTIFER = process.env.ADMIN_IDENTIFER;
const ADMIN_TOKEN_SECRET = process.env.ADMIN_TOKEN_SECRET;

//  bkash
const BKASH_USERNAME = process.env.BKASH_USERNAME
const BKASH_PASSWORD = process.env.BKASH_PASSWORD
const BKASH_APP_KEY = process.env.BKASH_APP_KEY
const BKASH_APP_SECRET = process.env.BKASH_APP_SECRET
const BKASH_TOKEN_GET = process.env.BKASH_TOKEN_GET
const BKASH_CREATE_PAYMENT = process.env.BKASH_CREATE_PAYMENT
const BKASH_EXECUTE = process.env.BKASH_EXECUTE
const BKASH_CALLBACK_URL = process.env.BKASH_CALLBACK_URL
const BKASH_RESPONSE_STATUS = process.env.BKASH_RESPONSE_STATUS

export {
    Port,
    MONGO_URL,
    IMG_BB_API_KEY,
    ADMIN_IDENTIFER,
    ADMIN_TOKEN_SECRET,

    //  bkash
    BKASH_USERNAME , BKASH_PASSWORD , BKASH_APP_KEY , BKASH_APP_SECRET,
    BKASH_TOKEN_GET, BKASH_CREATE_PAYMENT , BKASH_EXECUTE,BKASH_CALLBACK_URL,BKASH_RESPONSE_STATUS
};   
